on:
  pull_request:
    branches:
      - main
      
jobs:   
  build-run-test:
    name: Build, Run, and Test Application
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          version: '6.7.3'
          host: 'linux'
          target: 'desktop'
          arch: 'linux_gcc_64'
            
      #- name: Set environment variables
        #run: |
          #export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/vboxuser/Qt/6.7.3/gcc_64/lib
          #export PATH=$PATH:/home/vboxuser/squish-for-qt-8.1.0/bin/
          #export PATH=$PATH:/home/vboxuser/Qt/Tools/CMake/bin/
          #export QTDIR=$QTDIR:/home/vboxuser/Qt/
          #-DCMAKE_PREFIX_PATH:PATH=/Qt/6.7.3/gcc_64 
             
      - name: Build application
        run: |
          cmake -S sampleApp -B sampleApp/build -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH:PATH=/home/vboxuser/Qt/6.7.3/gcc_64 
          cmake --build sampleApp/build
        
      - name: Set squish environment variables
        run: |
          export SQUISH_PREFIX=/home/vboxuser/squish-for-qt-8.1.0
          export SQUISH_TESTCENTER_PREFIX=/home/vboxuser/testcenter-4.1.1-linux-x64
          export PATH=$PATH:$SQUISH_PREFIX/bin
          export PATH=$PATH:$SQUISH_TESTCENTER_PREFIX/bin

      - name: Setup AUT
        run: |
          startaut --port=9999 sampleAppl/build/appsampleApp &

      - name: Setup squishserver
        run: |
          echo "ALLOWED_HOSTS=*" > $SQUISH_PREFIX/etc/squishserverrc
          squishserver --config addAppPath sampleApp/build
          squishserver --config addAttachableAUT appsampleApp localhost:9999
          squishserver --verbose --daemon

      - name: Setup testcenter
        run: |
          testcenter --start
          
      - name: Run testsuites
        #run: |
          #./run squishrunner bash script

      - name: Clean up
        run: | 
          testcenter stop
          squishserver --stop
          kill %1
