on:
  pull_request:
    branches:
      - hong-updateTestScripts-2
      
jobs:   
  build-run-test:
    name: Build, Run, and Test Application
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
             
      - name: Execute
        run: |
          set -a; source /home/tony/Desktop/final_deliverable/GDMS-Final-Project/.env.paths; set +a
          cmake -S sampleApp -B sampleApp/build -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH:PATH=$SQUISH_GCC_PATH
          cmake --build sampleApp/build
          chmod +x automated_tests_script.sh
          ./automate_tests_script.sh

      #- name: Setup AUT
      #  run: |
      #    set -a; source .env.paths; set +a
      #    startaut --port=9999 sampleApp/build/appsampleApp &

      #- name: Setup squishserver
      #  working-directory: /home/vboxuser/
      #  run: |
      #    set -a; source .env.paths; set +a
      #    squishserver --daemon

      #- name: Setup testcenter
      #  working-directory: /home/vboxuser/
      #  run: |
      #    testcenter start
          
      #- name: Run testsuites
      #  run: |
      #    set -a; source .env.paths; set +a
      #    chmod +x automated_test_script.sh
      #    ./automated_test_script.sh

      #- name: Clean up
      #  run: | 
      #    testcenter stop
      #    squishserver --stop
      #    kill %1
          
